[build.environment]
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
  NODE_VERSION = "13.11.0"

[build]
  publish = "dist"
  functions = "functions"
  command = "yarn build && yarn run build:server"
